/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForVendorsRouteImport } from './routes/for-vendors'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RequestRouteImport } from './routes/request'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated/wishlist'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as ListingSlugRouteImport } from './routes/listing.$slug'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated/account.profile'
import { Route as AuthenticatedVendorIndexRouteImport } from './routes/_authenticated/vendor/index'
import { Route as AuthenticatedVendorLeadsRouteImport } from './routes/_authenticated/vendor/leads'
import { Route as AuthenticatedVendorProfileRouteImport } from './routes/_authenticated/vendor/profile'
import { Route as AuthenticatedVendorCalendarListingIdRouteImport } from './routes/_authenticated/vendor/calendar.$listingId'
import { Route as AuthenticatedVendorListingsNewRouteImport } from './routes/_authenticated/vendor/listings.new'
import { Route as AuthenticatedVendorListingsListingIdEditRouteImport } from './routes/_authenticated/vendor/listings.$listingId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForVendorsRoute = ForVendorsRouteImport.update({
  id: '/for-vendors',
  path: '/for-vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingSlugRoute = ListingSlugRouteImport.update({
  id: '/listing/$slug',
  path: '/listing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/account/profile',
    path: '/account/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorIndexRoute =
  AuthenticatedVendorIndexRouteImport.update({
    id: '/vendor/',
    path: '/vendor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorLeadsRoute =
  AuthenticatedVendorLeadsRouteImport.update({
    id: '/vendor/leads',
    path: '/vendor/leads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorProfileRoute =
  AuthenticatedVendorProfileRouteImport.update({
    id: '/vendor/profile',
    path: '/vendor/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorCalendarListingIdRoute =
  AuthenticatedVendorCalendarListingIdRouteImport.update({
    id: '/vendor/calendar/$listingId',
    path: '/vendor/calendar/$listingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorListingsNewRoute =
  AuthenticatedVendorListingsNewRouteImport.update({
    id: '/vendor/listings/new',
    path: '/vendor/listings/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorListingsListingIdEditRoute =
  AuthenticatedVendorListingsListingIdEditRouteImport.update({
    id: '/vendor/listings/$listingId/edit',
    path: '/vendor/listings/$listingId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/for-vendors': typeof ForVendorsRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/listing/$slug': typeof ListingSlugRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/vendor/leads': typeof AuthenticatedVendorLeadsRoute
  '/vendor/profile': typeof AuthenticatedVendorProfileRoute
  '/vendor/': typeof AuthenticatedVendorIndexRoute
  '/vendor/calendar/$listingId': typeof AuthenticatedVendorCalendarListingIdRoute
  '/vendor/listings/new': typeof AuthenticatedVendorListingsNewRoute
  '/vendor/listings/$listingId/edit': typeof AuthenticatedVendorListingsListingIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/for-vendors': typeof ForVendorsRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/listing/$slug': typeof ListingSlugRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/vendor/leads': typeof AuthenticatedVendorLeadsRoute
  '/vendor/profile': typeof AuthenticatedVendorProfileRoute
  '/vendor': typeof AuthenticatedVendorIndexRoute
  '/vendor/calendar/$listingId': typeof AuthenticatedVendorCalendarListingIdRoute
  '/vendor/listings/new': typeof AuthenticatedVendorListingsNewRoute
  '/vendor/listings/$listingId/edit': typeof AuthenticatedVendorListingsListingIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/for-vendors': typeof ForVendorsRoute
  '/privacy': typeof PrivacyRoute
  '/request': typeof RequestRoute
  '/search': typeof SearchRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/listing/$slug': typeof ListingSlugRoute
  '/_authenticated/account/profile': typeof AuthenticatedAccountProfileRoute
  '/_authenticated/vendor/leads': typeof AuthenticatedVendorLeadsRoute
  '/_authenticated/vendor/profile': typeof AuthenticatedVendorProfileRoute
  '/_authenticated/vendor/': typeof AuthenticatedVendorIndexRoute
  '/_authenticated/vendor/calendar/$listingId': typeof AuthenticatedVendorCalendarListingIdRoute
  '/_authenticated/vendor/listings/new': typeof AuthenticatedVendorListingsNewRoute
  '/_authenticated/vendor/listings/$listingId/edit': typeof AuthenticatedVendorListingsListingIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/for-vendors'
    | '/privacy'
    | '/request'
    | '/search'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/reviews'
    | '/wishlist'
    | '/category/$slug'
    | '/events/$slug'
    | '/listing/$slug'
    | '/account/profile'
    | '/vendor/leads'
    | '/vendor/profile'
    | '/vendor/'
    | '/vendor/calendar/$listingId'
    | '/vendor/listings/new'
    | '/vendor/listings/$listingId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/for-vendors'
    | '/privacy'
    | '/request'
    | '/search'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/reviews'
    | '/wishlist'
    | '/category/$slug'
    | '/events/$slug'
    | '/listing/$slug'
    | '/account/profile'
    | '/vendor/leads'
    | '/vendor/profile'
    | '/vendor'
    | '/vendor/calendar/$listingId'
    | '/vendor/listings/new'
    | '/vendor/listings/$listingId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/for-vendors'
    | '/privacy'
    | '/request'
    | '/search'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/reviews'
    | '/_authenticated/wishlist'
    | '/category/$slug'
    | '/events/$slug'
    | '/listing/$slug'
    | '/_authenticated/account/profile'
    | '/_authenticated/vendor/leads'
    | '/_authenticated/vendor/profile'
    | '/_authenticated/vendor/'
    | '/_authenticated/vendor/calendar/$listingId'
    | '/_authenticated/vendor/listings/new'
    | '/_authenticated/vendor/listings/$listingId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ForVendorsRoute: typeof ForVendorsRoute
  PrivacyRoute: typeof PrivacyRoute
  RequestRoute: typeof RequestRoute
  SearchRoute: typeof SearchRoute
  TermsRoute: typeof TermsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  EventsSlugRoute: typeof EventsSlugRoute
  ListingSlugRoute: typeof ListingSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-vendors': {
      id: '/for-vendors'
      path: '/for-vendors'
      fullPath: '/for-vendors'
      preLoaderRoute: typeof ForVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$slug': {
      id: '/listing/$slug'
      path: '/listing/$slug'
      fullPath: '/listing/$slug'
      preLoaderRoute: typeof ListingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/profile': {
      id: '/_authenticated/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/': {
      id: '/_authenticated/vendor/'
      path: '/vendor'
      fullPath: '/vendor/'
      preLoaderRoute: typeof AuthenticatedVendorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/leads': {
      id: '/_authenticated/vendor/leads'
      path: '/vendor/leads'
      fullPath: '/vendor/leads'
      preLoaderRoute: typeof AuthenticatedVendorLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/profile': {
      id: '/_authenticated/vendor/profile'
      path: '/vendor/profile'
      fullPath: '/vendor/profile'
      preLoaderRoute: typeof AuthenticatedVendorProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/calendar/$listingId': {
      id: '/_authenticated/vendor/calendar/$listingId'
      path: '/vendor/calendar/$listingId'
      fullPath: '/vendor/calendar/$listingId'
      preLoaderRoute: typeof AuthenticatedVendorCalendarListingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/listings/new': {
      id: '/_authenticated/vendor/listings/new'
      path: '/vendor/listings/new'
      fullPath: '/vendor/listings/new'
      preLoaderRoute: typeof AuthenticatedVendorListingsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/listings/$listingId/edit': {
      id: '/_authenticated/vendor/listings/$listingId/edit'
      path: '/vendor/listings/$listingId/edit'
      fullPath: '/vendor/listings/$listingId/edit'
      preLoaderRoute: typeof AuthenticatedVendorListingsListingIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedVendorLeadsRoute: typeof AuthenticatedVendorLeadsRoute
  AuthenticatedVendorProfileRoute: typeof AuthenticatedVendorProfileRoute
  AuthenticatedVendorIndexRoute: typeof AuthenticatedVendorIndexRoute
  AuthenticatedVendorCalendarListingIdRoute: typeof AuthenticatedVendorCalendarListingIdRoute
  AuthenticatedVendorListingsNewRoute: typeof AuthenticatedVendorListingsNewRoute
  AuthenticatedVendorListingsListingIdEditRoute: typeof AuthenticatedVendorListingsListingIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
  AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
  AuthenticatedVendorLeadsRoute: AuthenticatedVendorLeadsRoute,
  AuthenticatedVendorProfileRoute: AuthenticatedVendorProfileRoute,
  AuthenticatedVendorIndexRoute: AuthenticatedVendorIndexRoute,
  AuthenticatedVendorCalendarListingIdRoute:
    AuthenticatedVendorCalendarListingIdRoute,
  AuthenticatedVendorListingsNewRoute: AuthenticatedVendorListingsNewRoute,
  AuthenticatedVendorListingsListingIdEditRoute:
    AuthenticatedVendorListingsListingIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ForVendorsRoute: ForVendorsRoute,
  PrivacyRoute: PrivacyRoute,
  RequestRoute: RequestRoute,
  SearchRoute: SearchRoute,
  TermsRoute: TermsRoute,
  CategorySlugRoute: CategorySlugRoute,
  EventsSlugRoute: EventsSlugRoute,
  ListingSlugRoute: ListingSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
